# Generated by Django 3.2.4 on 2021-06-24 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_auto_20210624_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 24, 19, 36, 35, 226692)),
        ),
        migrations.AddField(
            model_name='meetup',
            name='organizer_email',
            field=models.EmailField(default='2021-06-14', max_length=254),
            preserve_default=False,
        ),
    ]
