# Generated by Django 3.2.4 on 2021-06-24 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0005_auto_20210624_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 6, 24, 19, 39, 52, 218630)),
        ),
    ]
