# Generated by Django 3.2.4 on 2021-06-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_alter_meetup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='date',
            field=models.DateField(),
        ),
    ]
